import { MigrationInterface, QueryRunner } from "typeorm";

export class SchemaUpdate1770370513380 implements MigrationInterface {
    name = 'SchemaUpdate1770370513380'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "quote_request_coverages" DROP CONSTRAINT "quote_request_coverages_quote_request_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "quote_requests" DROP CONSTRAINT "quote_requests_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "carrier_quotes" DROP CONSTRAINT "carrier_quotes_quote_request_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "carrier_quotes" DROP CONSTRAINT "carrier_quotes_carrier_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "policies" DROP CONSTRAINT "policies_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "policies" DROP CONSTRAINT "policies_quote_request_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "policies" DROP CONSTRAINT "policies_carrier_quote_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "policies" DROP CONSTRAINT "policies_carrier_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_payments_user"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_payments_policy"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_phone"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_quote_request_coverages_quote_request_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_quote_requests_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_quote_requests_session_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_quote_requests_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_quote_requests_insurance_type_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_quote_requests_deleted_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_carrier_quotes_quote_request_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_carrier_quotes_carrier_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_carrier_quotes_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_policies_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_policies_carrier_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_policies_policy_number"`);
        await queryRunner.query(`DROP INDEX "public"."idx_policies_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_policies_expiration_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_policies_deleted_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_policy_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_stripe_payment_intent_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_created_at"`);
        // Handle existing null password_hash values before making it NOT NULL
        await queryRunner.query(`UPDATE "users" SET "password_hash" = 'PLACEHOLDER_NEEDS_RESET' WHERE "password_hash" IS NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "password_hash" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "email" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "account_status"`);
        await queryRunner.query(`CREATE TYPE "public"."users_account_status_enum" AS ENUM('active', 'locked', 'suspended')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "account_status" "public"."users_account_status_enum" NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "quote_request_coverages" ALTER COLUMN "is_selected" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quote_request_coverages" ALTER COLUMN "is_recommended" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quote_request_coverages" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quote_request_coverages" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "quote_requests" DROP COLUMN "insurance_type"`);
        await queryRunner.query(`CREATE TYPE "public"."quote_requests_insurance_type_enum" AS ENUM('commercial', 'personal')`);
        await queryRunner.query(`ALTER TABLE "quote_requests" ADD "insurance_type" "public"."quote_requests_insurance_type_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quote_requests" DROP COLUMN "request_type"`);
        await queryRunner.query(`CREATE TYPE "public"."quote_requests_request_type_enum" AS ENUM('new_business', 'renewal', 'quote_only')`);
        await queryRunner.query(`ALTER TABLE "quote_requests" ADD "request_type" "public"."quote_requests_request_type_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quote_requests" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."quote_requests_status_enum" AS ENUM('draft', 'submitted', 'processing', 'quotes_ready', 'quote_selected', 'purchased', 'expired')`);
        await queryRunner.query(`ALTER TABLE "quote_requests" ADD "status" "public"."quote_requests_status_enum" NOT NULL DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE "quote_requests" DROP COLUMN "address_type"`);
        await queryRunner.query(`CREATE TYPE "public"."quote_requests_address_type_enum" AS ENUM('physical', 'virtual')`);
        await queryRunner.query(`ALTER TABLE "quote_requests" ADD "address_type" "public"."quote_requests_address_type_enum"`);
        await queryRunner.query(`ALTER TABLE "quote_requests" ALTER COLUMN "consent_marketing" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quote_requests" ALTER COLUMN "consent_privacy_policy" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quote_requests" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quote_requests" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "quote_requests" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quote_requests" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "carriers" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "carriers" ALTER COLUMN "supports_personal" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "carriers" ALTER COLUMN "supports_commercial" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "carriers" DROP COLUMN "health_status"`);
        await queryRunner.query(`CREATE TYPE "public"."carriers_health_status_enum" AS ENUM('operational', 'degraded', 'down')`);
        await queryRunner.query(`ALTER TABLE "carriers" ADD "health_status" "public"."carriers_health_status_enum"`);
        await queryRunner.query(`ALTER TABLE "carriers" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "carriers" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "carriers" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "carriers" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "carrier_quotes" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."carrier_quotes_status_enum" AS ENUM('quoted', 'declined', 'referred', 'expired')`);
        await queryRunner.query(`ALTER TABLE "carrier_quotes" ADD "status" "public"."carrier_quotes_status_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "carrier_quotes" DROP COLUMN "insurance_type"`);
        await queryRunner.query(`CREATE TYPE "public"."carrier_quotes_insurance_type_enum" AS ENUM('commercial', 'personal')`);
        await queryRunner.query(`ALTER TABLE "carrier_quotes" ADD "insurance_type" "public"."carrier_quotes_insurance_type_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "carrier_quotes" ALTER COLUMN "generated_via_llm" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "carrier_quotes" ALTER COLUMN "cached" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "carrier_quotes" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "carrier_quotes" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "policies" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."policies_status_enum" AS ENUM('bound', 'active', 'cancelled', 'expired', 'pending_cancellation')`);
        await queryRunner.query(`ALTER TABLE "policies" ADD "status" "public"."policies_status_enum" NOT NULL DEFAULT 'bound'`);
        await queryRunner.query(`ALTER TABLE "policies" DROP COLUMN "payment_plan"`);
        await queryRunner.query(`CREATE TYPE "public"."policies_payment_plan_enum" AS ENUM('annual', 'monthly', 'quarterly')`);
        await queryRunner.query(`ALTER TABLE "policies" ADD "payment_plan" "public"."policies_payment_plan_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "policies" ALTER COLUMN "auto_renewal" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "policies" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "policies" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "policies" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "policies" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TYPE "public"."payment_type_enum" RENAME TO "payment_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."payments_payment_type_enum" AS ENUM('initial', 'recurring', 'endorsement', 'one_time')`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "payment_type" TYPE "public"."payments_payment_type_enum" USING "payment_type"::"text"::"public"."payments_payment_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payment_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."payment_status_enum" RENAME TO "payment_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('pending', 'succeeded', 'failed', 'refunded')`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "status" TYPE "public"."payments_status_enum" USING "status"::"text"::"public"."payments_status_enum"`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."payment_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."payment_method_enum" RENAME TO "payment_method_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."payments_payment_method_enum" AS ENUM('credit_card', 'ach', 'check')`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "payment_method" TYPE "public"."payments_payment_method_enum" USING "payment_method"::"text"::"public"."payments_payment_method_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payment_method_enum_old"`);
        await queryRunner.query(`ALTER TABLE "quote_request_coverages" ADD CONSTRAINT "FK_be16256b57c6fe54a9539026fd7" FOREIGN KEY ("quote_request_id") REFERENCES "quote_requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quote_requests" ADD CONSTRAINT "FK_462bacc0dd1384c719b15e641b8" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carrier_quotes" ADD CONSTRAINT "FK_ed4e7d9d70f6e3e4ca1854908d2" FOREIGN KEY ("quote_request_id") REFERENCES "quote_requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carrier_quotes" ADD CONSTRAINT "FK_6903c931febbbbebe9e52e548d3" FOREIGN KEY ("carrier_id") REFERENCES "carriers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "policies" ADD CONSTRAINT "FK_0192750cdb713afc762287d6944" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "policies" ADD CONSTRAINT "FK_9e7dc7d204312749f673f2d8798" FOREIGN KEY ("quote_request_id") REFERENCES "quote_requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "policies" ADD CONSTRAINT "FK_130046fb7224bd2c95424e0d33e" FOREIGN KEY ("carrier_quote_id") REFERENCES "carrier_quotes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "policies" ADD CONSTRAINT "FK_34e0370375891536f8c85dfe9a5" FOREIGN KEY ("carrier_id") REFERENCES "carriers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_427785468fb7d2733f59e7d7d39" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_9be2fabf26c6630d807a792adfd" FOREIGN KEY ("policy_id") REFERENCES "policies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_9be2fabf26c6630d807a792adfd"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_427785468fb7d2733f59e7d7d39"`);
        await queryRunner.query(`ALTER TABLE "policies" DROP CONSTRAINT "FK_34e0370375891536f8c85dfe9a5"`);
        await queryRunner.query(`ALTER TABLE "policies" DROP CONSTRAINT "FK_130046fb7224bd2c95424e0d33e"`);
        await queryRunner.query(`ALTER TABLE "policies" DROP CONSTRAINT "FK_9e7dc7d204312749f673f2d8798"`);
        await queryRunner.query(`ALTER TABLE "policies" DROP CONSTRAINT "FK_0192750cdb713afc762287d6944"`);
        await queryRunner.query(`ALTER TABLE "carrier_quotes" DROP CONSTRAINT "FK_6903c931febbbbebe9e52e548d3"`);
        await queryRunner.query(`ALTER TABLE "carrier_quotes" DROP CONSTRAINT "FK_ed4e7d9d70f6e3e4ca1854908d2"`);
        await queryRunner.query(`ALTER TABLE "quote_requests" DROP CONSTRAINT "FK_462bacc0dd1384c719b15e641b8"`);
        await queryRunner.query(`ALTER TABLE "quote_request_coverages" DROP CONSTRAINT "FK_be16256b57c6fe54a9539026fd7"`);
        await queryRunner.query(`CREATE TYPE "public"."payment_method_enum_old" AS ENUM('credit_card', 'ach', 'check')`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "payment_method" TYPE "public"."payment_method_enum_old" USING "payment_method"::"text"::"public"."payment_method_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."payments_payment_method_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."payment_method_enum_old" RENAME TO "payment_method_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."payment_status_enum_old" AS ENUM('pending', 'succeeded', 'failed', 'refunded')`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "status" TYPE "public"."payment_status_enum_old" USING "status"::"text"::"public"."payment_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."payment_status_enum_old" RENAME TO "payment_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."payment_type_enum_old" AS ENUM('initial', 'recurring', 'endorsement', 'one_time')`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "payment_type" TYPE "public"."payment_type_enum_old" USING "payment_type"::"text"::"public"."payment_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."payments_payment_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."payment_type_enum_old" RENAME TO "payment_type_enum"`);
        await queryRunner.query(`ALTER TABLE "policies" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "policies" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "policies" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "policies" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "policies" ALTER COLUMN "auto_renewal" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "policies" DROP COLUMN "payment_plan"`);
        await queryRunner.query(`DROP TYPE "public"."policies_payment_plan_enum"`);
        await queryRunner.query(`ALTER TABLE "policies" ADD "payment_plan" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "policies" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."policies_status_enum"`);
        await queryRunner.query(`ALTER TABLE "policies" ADD "status" character varying(20) DEFAULT 'bound'`);
        await queryRunner.query(`ALTER TABLE "carrier_quotes" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "carrier_quotes" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "carrier_quotes" ALTER COLUMN "cached" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "carrier_quotes" ALTER COLUMN "generated_via_llm" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "carrier_quotes" DROP COLUMN "insurance_type"`);
        await queryRunner.query(`DROP TYPE "public"."carrier_quotes_insurance_type_enum"`);
        await queryRunner.query(`ALTER TABLE "carrier_quotes" ADD "insurance_type" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "carrier_quotes" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."carrier_quotes_status_enum"`);
        await queryRunner.query(`ALTER TABLE "carrier_quotes" ADD "status" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "carriers" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "carriers" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "carriers" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "carriers" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "carriers" DROP COLUMN "health_status"`);
        await queryRunner.query(`DROP TYPE "public"."carriers_health_status_enum"`);
        await queryRunner.query(`ALTER TABLE "carriers" ADD "health_status" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "carriers" ALTER COLUMN "supports_commercial" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "carriers" ALTER COLUMN "supports_personal" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "carriers" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quote_requests" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "quote_requests" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quote_requests" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "quote_requests" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quote_requests" ALTER COLUMN "consent_privacy_policy" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quote_requests" ALTER COLUMN "consent_marketing" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quote_requests" DROP COLUMN "address_type"`);
        await queryRunner.query(`DROP TYPE "public"."quote_requests_address_type_enum"`);
        await queryRunner.query(`ALTER TABLE "quote_requests" ADD "address_type" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "quote_requests" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."quote_requests_status_enum"`);
        await queryRunner.query(`ALTER TABLE "quote_requests" ADD "status" character varying(50) DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE "quote_requests" DROP COLUMN "request_type"`);
        await queryRunner.query(`DROP TYPE "public"."quote_requests_request_type_enum"`);
        await queryRunner.query(`ALTER TABLE "quote_requests" ADD "request_type" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quote_requests" DROP COLUMN "insurance_type"`);
        await queryRunner.query(`DROP TYPE "public"."quote_requests_insurance_type_enum"`);
        await queryRunner.query(`ALTER TABLE "quote_requests" ADD "insurance_type" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quote_request_coverages" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "quote_request_coverages" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quote_request_coverages" ALTER COLUMN "is_recommended" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quote_request_coverages" ALTER COLUMN "is_selected" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "account_status"`);
        await queryRunner.query(`DROP TYPE "public"."users_account_status_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "account_status" character varying(20) NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "email" TYPE character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "password_hash" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "password_hash" TYPE character varying(255)`);
        await queryRunner.query(`CREATE INDEX "IDX_payments_created_at" ON "payments" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_stripe_payment_intent_id" ON "payments" ("stripe_payment_intent_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_status" ON "payments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_policy_id" ON "payments" ("policy_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_user_id" ON "payments" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_policies_deleted_at" ON "policies" ("deleted_at") `);
        await queryRunner.query(`CREATE INDEX "idx_policies_expiration_date" ON "policies" ("expiration_date") `);
        await queryRunner.query(`CREATE INDEX "idx_policies_status" ON "policies" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_policies_policy_number" ON "policies" ("policy_number") `);
        await queryRunner.query(`CREATE INDEX "idx_policies_carrier_id" ON "policies" ("carrier_id") `);
        await queryRunner.query(`CREATE INDEX "idx_policies_user_id" ON "policies" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_carrier_quotes_status" ON "carrier_quotes" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_carrier_quotes_carrier_id" ON "carrier_quotes" ("carrier_id") `);
        await queryRunner.query(`CREATE INDEX "idx_carrier_quotes_quote_request_id" ON "carrier_quotes" ("quote_request_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_quote_requests_deleted_at" ON "quote_requests" ("deleted_at") `);
        await queryRunner.query(`CREATE INDEX "idx_quote_requests_insurance_type_status" ON "quote_requests" ("insurance_type", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_quote_requests_status" ON "quote_requests" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_quote_requests_session_id" ON "quote_requests" ("session_id") `);
        await queryRunner.query(`CREATE INDEX "idx_quote_requests_user_id" ON "quote_requests" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_quote_request_coverages_quote_request_id" ON "quote_request_coverages" ("quote_request_id") `);
        await queryRunner.query(`CREATE INDEX "idx_users_email" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "idx_users_phone" ON "users" ("phone") `);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_payments_policy" FOREIGN KEY ("policy_id") REFERENCES "policies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_payments_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "policies" ADD CONSTRAINT "policies_carrier_id_fkey" FOREIGN KEY ("carrier_id") REFERENCES "carriers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "policies" ADD CONSTRAINT "policies_carrier_quote_id_fkey" FOREIGN KEY ("carrier_quote_id") REFERENCES "carrier_quotes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "policies" ADD CONSTRAINT "policies_quote_request_id_fkey" FOREIGN KEY ("quote_request_id") REFERENCES "quote_requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "policies" ADD CONSTRAINT "policies_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carrier_quotes" ADD CONSTRAINT "carrier_quotes_carrier_id_fkey" FOREIGN KEY ("carrier_id") REFERENCES "carriers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carrier_quotes" ADD CONSTRAINT "carrier_quotes_quote_request_id_fkey" FOREIGN KEY ("quote_request_id") REFERENCES "quote_requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quote_requests" ADD CONSTRAINT "quote_requests_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quote_request_coverages" ADD CONSTRAINT "quote_request_coverages_quote_request_id_fkey" FOREIGN KEY ("quote_request_id") REFERENCES "quote_requests"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
